version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `.` directory
    directory: '.'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'monthly'
      time: '03:00'
    groups:
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-plugin-*'
          - 'eslint-config-*'
          - '@eslint/*'
          - 'typescript-eslint'
          - '@typescript-eslint/*'
      jest:
        patterns:
          - 'jest'
          - '@jest/*'
          - 'ts-jest'
          - '@types/jest'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
